ARTIGOS = [
    {'artigo': 'Art. 170 I', 'descricao': 'ELOGIO PUBLICADO EM BOLETIM POR DOAÇÃO DE SANGUE'},
{'artigo': 'Art. 170 II', 'descricao': 'ELOGIO PUBLICADO EM BOLETIM, EXCETO POR DOAÇÃO DE SANGUE'},
{'artigo': 'Art. 170 III', 'descricao': 'REFERÊNCIA ELOGIOSA - CPA'},
{'artigo': 'Art. 142 I a', 'descricao': ' desrespeitar as normas de boas maneiras e/ou convenções sociais;,'},
{'artigo': 'Art. 142 I b', 'descricao': ' faltar com urbanidade, camaradagem ou cortesia'},
{'artigo': 'Art. 142 II a', 'descricao': 'utilizar gírias, palavras de calão, gestos obscenos ou termos pornográficos no interior do aquartelamento;'},
{'artigo': 'Art. 142 II b', 'descricao': 'possuir escritos, figuras ou revistas pornográficas ou do gênero no interior do aquartelamento;'},
{'artigo': 'Art. 142 II c', 'descricao': 'perturbar o sossego em local impróprio;,'},
{'artigo': 'Art. 142 II d', 'descricao': 'utilizar-se do anonimato;,'},
{'artigo': 'Art. 142 II e', 'descricao': 'portar-se de modo inconveniente e sem compostura, faltando aos preceitos da boa educação e moral;'},
{'artigo': 'Art. 142 II f', 'descricao': 'dirigir, quando uniformizado e de folga, gracejos a alguém;'},
{'artigo': 'Art. 142 II g', 'descricao': 'demonstrar intimidade com outrem, mediante atos ou gestos comprometedores, estando uniformizado e de folga.'},
{'artigo': 'Art. 142 III a', 'descricao': 'desrespeitar, desconsiderar ou discutir com o companheiro de curso;'},
{'artigo': 'Art. 142 III b', 'descricao': 'tecer comentário inoportuno ou em tom de críticas que não sejam de sua competência;,'},
{'artigo': 'Art. 142 III c', 'descricao': 'espalhar boatos ou notícias tendenciosas, em prejuízo da boa ordem civil ou militar, ou do nome da Polícia Militar ;'},
{'artigo': 'Art. 142 III d', 'descricao': 'frequentar lugares incompatíveis com sua condição de Policial Militar, uniformizado ou mesmo estando de folga e em trajes civis;'},
{'artigo': 'Art. 142 III e', 'descricao': 'manter relações de amizade com pessoas de comprovada má reputação ou de conduta social reprovável ou irregular, ou apresentar-se publicamente com elas;'},
{'artigo': 'Art. 142 III f', 'descricao': 'praticar violência ou qualquer outro ato que denigra a imagem da APM/ES;,'},
{'artigo': 'Art. 142 III g', 'descricao': 'embriagar-se ou apresentar-se em estado de embriaguez em público, independente de constatação médica, desde que visível o estado;'},
{'artigo': 'Art. 142 III h', 'descricao': 'fazer uso de qualquer bebida alcoólica em eventos policiais militares, quando de serviço ou em representação;'},
{'artigo': 'Art. 142 III i', 'descricao': 'faltar à verdade, exceto na condição de acusado nos inquéritos e processos penais;'},
{'artigo': 'Art. 142 III j', 'descricao': 'tentar se esquivar da responsabilidade em ações ou omissões, as quais sejam atentatórios ao decoro moral, ético e dos valores militares;'},
{'artigo': 'Art. 142 III k', 'descricao': 'dirigir, quando uniformizado e de serviço, gracejos a alguém;'},
{'artigo': 'Art. 142 III l', 'descricao': 'demonstrar intimidade com outrem, mediante atos ou gestos comprometedores, estando uniformizado e de serviço;'},
{'artigo': 'Art. 142 III m', 'descricao': 'ter conduta incompatível com os princípios da hierarquia, ética e valores militares.'},
{'artigo': 'Art. 143 I a', 'descricao': 'levantar após o horário previsto de Alvorada;,'},
{'artigo': 'Art. 143 I b', 'descricao': 'perturbar o sossego após o horário de silêncio.,'},
{'artigo': 'Art. 143 II a', 'descricao': 'deixar de entregar documentação no prazo estabelecido;,'},
{'artigo': 'Art. 143 II b', 'descricao': 'entregar requerimento de solicitações diversas ao Secretário da turma, de forma intempestiva, trazendo transtorno administrativo à Escola.'},
{'artigo': 'Art. 143 II c', 'descricao': 'chegar atrasado a qualquer atividade policial, tal como expediente, instrução, serviço ou outras chamadas das quais deva participar. '},
{'artigo': 'Art. 143 III a', 'descricao': 'adentrar ao quartel, após as 22 horas, sem autorização do Comandante da respectiva Escola ou do Oficial de Dia;'},
{'artigo': 'Art. 143 III b', 'descricao': 'faltar à aula, instrução ou outro ato de serviço em que deva tomar parte ou assistir;'},
{'artigo': 'Art. 143 III c', 'descricao': 'gozar a folga a que teria direito em serviço no qual faltou justificadamente;,'},
{'artigo': 'Art. 143 III d', 'descricao': 'deixar de entrar em contato com a Escola em tempo hábil para informar o motivo de atraso ou falta, permanecendo em destino ignorado (DI), trazendo transtornos administrativos;'},
{'artigo': 'Art. 144 I a', 'descricao': 'deixar de comunicar ao superior a execução de ordem recebida;,'},
{'artigo': 'Art. 144 I b', 'descricao': 'deixar de comunicar à Escola qualquer alteração no seu endereço, telefones e outros dados que deva manter atualizados junto a APM/ES;'},
{'artigo': 'Art. 144 I c', 'descricao': 'conversar com a sentinela, em seu posto, salvo sobre objeto de serviço.'},
{'artigo': 'Art. 144 II a', 'descricao': 'retardar a execução de qualquer ordem;,'},
{'artigo': 'Art. 144 II b', 'descricao': 'invocar circunstâncias de matrimônio, de encargo de família ou de crença religiosa, para se eximir de obrigações funcionais;'},
{'artigo': 'Art. 144 II c', 'descricao': 'não levar falta ou irregularidade que presenciar, ou de que tiver ciência e não lhe couber reprimir, ao conhecimento de autoridade competente;'},
{'artigo': 'Art. 144 II d', 'descricao': 'praticar, quando em gozo de licença ou dispensa por problemas de saúde, atividade incompatível com o quadro clínico apresentado;'},
{'artigo': 'Art. 144 II e', 'descricao': 'comercializar qualquer tipo de produto ou serviço no âmbito da APM/ES, sem autorização;'},
{'artigo': 'Art. 144 II f', 'descricao': 'manter contato pessoal, fora da APM/ES, com professores civis ou militares, para tratar de assuntos de interesse pessoal ou coletivo, referentes ao ensino na APM/ES;'},
{'artigo': 'Art. 144 II g', 'descricao': 'deixar de entregar dispensa médica ao Chefe de Curso, por meio do Auxiliar P/1, no prazo de até 24 horas após a emissão, ou não viabilizar a sua entrega por outrem, em caso de impedimento do discente, ou quando o afastamento ocorrer em dia não letivo;'},
{'artigo': 'Art. 144 II h', 'descricao': 'deixar de preencher a Comunicação de Acidente, dentro do prazo, caso venha a se lesionar, mesmo não estando de serviço ou em instrução;'},
{'artigo': 'Art. 144 II i', 'descricao': 'não tomar conhecimento das ordens e atividades programadas pela APM/ES, em razão de sua ausência em alguma chamada.'},
{'artigo': 'Art. 144 III a', 'descricao': 'alegar, sem fundamento clínico, impossibilidade de trabalhar ou de comparecer a escola ou simular doença ou fato impeditivo para se esquivar ao cumprimento de qualquer dever;'},
{'artigo': 'Art. 144 III b', 'descricao': 'deixar de acatar ordem legal de superior hierárquico ou de militar de serviço ou de discente com ascendência funcional perante a turma, em razão do desempenho de função prevista neste Manual;'},
{'artigo': 'Art. 144 III c', 'descricao': 'não informar ao Chefe de Curso as ocorrências ou fatos relevantes que tenha se envolvido;,'},
{'artigo': 'Art. 144 III d', 'descricao': 'deixar de informar ao Chefe de Curso quando for dispensado por profissional da saúde;,'},
{'artigo': 'Art. 144 III e', 'descricao': 'sair do quartel sem a devida autorização do Chefe de Curso, Oficial de Dia ou Comando da Escola;'},
{'artigo': 'Art. 144 III f', 'descricao': 'recusar-se a exibir à sentinela ou ao superior hierárquico, quando por ele solicitado, objeto ou volume, ao entrar ou sair da APM/ES ou quando for solicitado;'},
{'artigo': 'Art. 144 III g', 'descricao': 'plagiar recurso de transgressão escolar e/ou disciplinar;,'},
{'artigo': 'Art. 144 III h', 'descricao': 'exercer atividade remunerada paralela ao curso de formação;,'},
{'artigo': 'Art. 145 I a', 'descricao': 'alegar desconhecimento de suas obrigações e deveres previstos neste Manual.,'},
{'artigo': 'Art. 145 II a', 'descricao': 'conversar, sentar-se ou fumar, onde isso não seja permitido, a sentinela da hora ou plantão da hora, ou, ainda, consentir na formação ou permanência de grupo ou de pessoas junto ao seu posto de serviço;'},
{'artigo': 'Art. 145 II b', 'descricao': 'mostrar-se desatento e desinteressado no serviço;,'},
{'artigo': 'Art. 145 II c', 'descricao': 'deixar de identificar e notificar as falhas na apresentação pessoal, armamento e uso de equipamentos, assiduidade e anúncio prestado pelos subordinados quando na função de fiscal de pelotão, comandante da guarda ou Fiscal de Dia;'},
{'artigo': 'Art. 145 II d', 'descricao': 'demonstrar falta de zelo na preparação ou execução de instrução;,'},
{'artigo': 'Art. 145 II e', 'descricao': 'Quando escalado em serviço operacional externo ou interno, não efetuar ou executar incorretamente, como motorista, a manutenção e limpeza de 1º escalão da viatura; '},
{'artigo': 'Art. 145 II f', 'descricao': 'manusear celular ou qualquer outro aparelho eletrônico durante turno de serviço sem que a ação tenha motivação com o serviço executado.,'},
{'artigo': 'Art. 145 III a', 'descricao': 'trabalhar mal ou descumprir as normas regulamentares no exercício das funções e atividades de serviço interno elencadas no Título XI deste Manual do Aluno, na condução de instrução ou no exercício de encargo;'},
{'artigo': 'Art. 145 III b', 'descricao': 'desrespeitar, desconsiderar ou ofender o cidadão por palavras, atos ou gestos, durante estágio ou empenho operacional e em outras situações de serviço;'},
{'artigo': 'Art. 145 III c', 'descricao': 'dormir em serviço de policiamento, vigilância ou segurança de pessoas ou instalações, salvo quando autorizado;'},
{'artigo': 'Art. 145 III d', 'descricao': 'abandonar local ou posto de serviço ou qualquer outra atividade escolar;,'},
{'artigo': 'Art. 145 III e', 'descricao': 'permutar serviço sem permissão de quem de direito;,'},
{'artigo': 'Art. 145 III f', 'descricao': 'descumprir determinações impostas ao pessoal de serviço.,'},
{'artigo': 'Art. 146 I a', 'descricao': 'utilizar uniforme em desalinho, amarrotado, mal passado, com vincos mal feitos ou sem vincos;'},
{'artigo': 'Art. 146 I b', 'descricao': 'usar calçado mal engraxado ou sem brilho;,'},
{'artigo': 'Art. 146 II a', 'descricao': 'utilizar peça do uniforme sujo, rasgado, com tecido desbotado ou manchado, com fios soltos, faltando botões ou com qualquer outro tipo de alteração;'},
{'artigo': 'Art. 146 II b', 'descricao': 'utilizar insígnia ou fivela do cinto sujo, descascado ou sem o devido polimento ou com qualquer outro tipo de alteração;'},
{'artigo': 'Art. 146 II c', 'descricao': 'ser flagrado com o cinto de guarnição puído, porta objetos rasgados ou com peças plásticas, de metal, botões ou velcros inoperantes;'},
{'artigo': 'Art. 146 II d', 'descricao': 'utilizar tarjeta de identificação desbotada, suja ou com qualquer outro tipo de alteração;'},
{'artigo': 'Art. 146 II e', 'descricao': 'utilizar uniforme incompleto (com peças desfalcadas);,'},
{'artigo': 'Art. 146 II f', 'descricao': 'sobrepor acessórios ou peças não regulamentares sobre o uniforme;,'},
{'artigo': 'Art. 146 II g', 'descricao': 'utilizar chinelo ou tênis fora do padrão estabelecido;,'},
{'artigo': 'Art. 146 II h', 'descricao': 'deixar de utilizar a cobertura regulamentar;,'},
{'artigo': 'Art. 146 II i', 'descricao': 'deixar de utilizar a tarjeta ou plaqueta de identificação;,'},
{'artigo': 'Art. 146 II j', 'descricao': 'portar o telefone celular ostensivamente sobrepondo peças do fardamento;,'},
{'artigo': 'Art. 146 II k', 'descricao': 'deixar de portar caneta padronizada pela escola ou bloco para anotações;,'},
{'artigo': 'Art. 146 II l', 'descricao': 'deixar de portar outros objetos quando determinado pelo Comando da Escola;,'},
{'artigo': 'Art. 146 II m', 'descricao': 'não seguir a padronização definida para o posicionamento dos itens previstos no cinto de guarnição;,'},
{'artigo': 'Art. 146 II n', 'descricao': 'utilizar equipamento de proteção individual (EPI) fora do local de instrução;,'},
{'artigo': 'Art. 146 II o', 'descricao': 'utilizar óculos de sol, quando uniformizado, sem recomendação médica;'},
{'artigo': 'Art. 146 II p', 'descricao': 'deixar a manga da camisa de gola olímpica aparente sob o uniforme;,'},
{'artigo': 'Art. 146 II q', 'descricao': 'utilizar fones de ouvido, estando uniformizado;'},
{'artigo': 'Art. 146 II r', 'descricao': 'utilizar cordões em geral, piercings ou congêneres, pulseiras, gargantilhas e braceletes, aparentes (visíveis);'},
{'artigo': 'Art. 146 II s', 'descricao': 'utilizar, a discente, mais de um brinco em cada orelha ou em desacordo com este Manual;'},
{'artigo': 'Art. 146 II t', 'descricao': 'utilizar, a discente, o coque mal feito ou o cabelo em desacordo com as normas previstas no RUIPMES.'},
{'artigo': 'Art. 146 II u', 'descricao': 'hastear ou arriar bandeira ou insígnia, sem ordem para tal ou de forma inadequada.'},
{'artigo': 'Art. 146 III a', 'descricao': 'usar uniforme com a identificação de outro militar;,'},
{'artigo': 'Art. 146 III b', 'descricao': 'faltar com o respeito aos símbolos nacionais, estaduais, municipais ou que representem a Escola ou a Corporação;'},
{'artigo': 'Art. 146 III c', 'descricao': 'descumprir normas complementares da Escola relativas ao uso e à padronização do uniforme;,'},
{'artigo': 'Art. 146 III d', 'descricao': 'apresentar-se para o serviço ou instrução com uniforme diferente do previsto;,'},
{'artigo': 'Art. 146 III e', 'descricao': 'descumprir as demais normas previstas no Regulamento de Uniformes da Polícia Militar (RUIPMES);,'},
{'artigo': 'Art. 146 III f', 'descricao': 'não possuir todos os uniformes de posse obrigatória na APM/ES.,'},
{'artigo': 'Art. 147 I a', 'descricao': 'extraviar documento de identidade militar;,'},
{'artigo': 'Art. 147 I b', 'descricao': 'deixar de portar ou ter ao seu alcance, em qualquer situação, o seu documento de identidade militar, estando ou não uniformizado, ou de exibi-lo quando solicitado;'},
{'artigo': 'Art. 147 I c', 'descricao': 'deixar objeto pessoal ou peça de uso diário abandonado ou em local indevido;,'},
{'artigo': 'Art. 147 I d', 'descricao': 'não ter o devido zelo na apresentação ou elaboração de documentos ou em desacordo com as normas oficiais de sua confecção;,'},
{'artigo': 'Art. 147 I e', 'descricao': 'encaminhar documento sem assinatura ou identificação.,'},
{'artigo': 'Art. 147 II a', 'descricao': 'danificar, extraviar ou inutilizar, por ação ou omissão, documentos,armamento e outros bens pertencentes ao patrimônio público ou particular, que estejam ou não sob sua responsabilidade;'},
{'artigo': 'Art. 147 II b', 'descricao': 'apresentar documentos com termos desrespeitosos ou com argumentosfalsos ou de má fé;,'},
{'artigo': 'Art. 147 II c', 'descricao': 'encaminhar documento desrespeitando a cadeia de comando;,'},
{'artigo': 'Art. 147 II d', 'descricao': 'não realizar a manutenção no armamento sob sua responsabilidade;,'},
{'artigo': 'Art. 147 II e', 'descricao': 'rasurar livros, fichas de solicitação, folhas de alterações, ou outros documentos, bem como lançar quaisquer outras matérias estranhas às finalidades destes documentos;'},
{'artigo': 'Art. 147 II f', 'descricao': 'subtrair, extraviar, danificar ou inutilizar documentos de interesse da administração pública ou de terceiros;'},
{'artigo': 'Art. 147 II g', 'descricao': 'ser flagrado durante o expediente letivo com o armamento, carregador ou algema sujo ou mal conservado ou não portar junto ao cinto de guarnição os carregadores reservas ou a algema;'},
{'artigo': 'Art. 147 III a', 'descricao': 'abandonar ou deixar em local inapropriado armamento, equipamento ou material da fazenda pública;'},
{'artigo': 'Art. 147 III b', 'descricao': 'manter em seu poder, indevidamente, bens de particulares ou da Fazenda Pública;'},
{'artigo': 'Art. 147 III c', 'descricao': 'não devolver material acautelado dentro do prazo determinado;,'},
{'artigo': 'Art. 147 III d', 'descricao': 'deixar de utilizar colete balístico durante serviço interno em atividade para a qual o item for de uso obrigatório;,'},
{'artigo': 'Art. 147 III e', 'descricao': 'ser flagrado durante qualquer escala de serviço interno de guarda ou de policiamento externo com o armamento, carregador ou algema sujo ou mal manutenido ou não portar junto ao cinto de guarnição os carregadores reservas ou a algema;'},
{'artigo': 'Art. 147 III f', 'descricao': 'deixar de portar o cordão fiel ou estar com o fiel desconectado do respetivo armamento.,'},
{'artigo': 'Art. 148 I a', 'descricao': 'transitar por locais não autorizados, exceto em relação a alojamentos (vide incisos II e III deste artigo);'},
{'artigo': 'Art. 148 I b', 'descricao': 'permanecer em dependência de Organização Militar (OM) ou da APM/ES, sem permissão de autoridade competente;'},
{'artigo': 'Art. 148 I c', 'descricao': 'adentrar o discente, sem permissão ou ordem, em lugar onde a entrada seja vedada;'},
{'artigo': 'Art. 148 I d', 'descricao': 'entrar ou sair de Organização Militar, sem prévio conhecimento ou ordem da autoridade competente;'},
{'artigo': 'Art. 148 I e', 'descricao': 'deixar o Aluno Oficial, ao entrar em Organização Militar diversa da APM/ES, de dar ciência da sua presença ao Oficial de Dia, e, em seguida, de procurar o Subcomandante da mesma ou o seu substituto legal;'},
{'artigo': 'Art. 148 I f', 'descricao': 'deixar os discentes da Escola de Formação e Aperfeiçoamento de Praças, ao entrar em Organização Militar diversa da APM/ES, de apresentar-se ao Oficial de Dia ou ao seu substituto legal;'},
{'artigo': 'Art. 148 I g', 'descricao': 'permanecer em trajes civis no interior da APM/ES ou de qualquer outra OM;,'},
{'artigo': 'Art. 148 I h', 'descricao': 'deslocar em trajes civis do portão das armas a qualquer local, dentro da APM/ES ou de OM, diverso do vestiário;'},
{'artigo': 'Art. 148 I i', 'descricao': 'utilizar traje civil incompatível com o decoro ou condição de Militar, dentro da APM/ES ou OM;'},
{'artigo': 'Art. 148 I j', 'descricao': 'usar a cantina no horário de aula;,'},
{'artigo': 'Art. 148 I k', 'descricao': 'alimentar-se no pátio do quartel, fora das áreas das cantinas;'},
{'artigo': 'Art. 148 I l', 'descricao': 'transitar ou sair do vestiário ou alojamento, mesmo em pequeno percurso, com trajes desfalcados ou impróprios ou atentatórios à moral e aos bons costumes;'},
{'artigo': 'Art. 148 I m', 'descricao': 'dirigir-se a outras seções da APM/ES, sem autorização do Comandante ou Chefe imediato;'},
{'artigo': 'Art. 148 I n', 'descricao': 'transitar pelo saguão da administração da APM/ES, exceção feita aos alunos no serviço de guarda do quartel ou em decorrência de serviço durante as solenidades;'},
{'artigo': 'Art. 148 I o', 'descricao': 'permanecer no vestiário durante o horário de aula ou instrução, salvo por prescrição médica.'},
{'artigo': 'Art. 148 II a', 'descricao': 'fumar em locais proibidos ou sujeitos à Administração Militar;,'},
{'artigo': 'Art. 148 II b', 'descricao': 'promover ou tomar parte em jogos proibidos, ou jogar a dinheiro os permitidos, em área militar ou sob a administração militar;'},
{'artigo': 'Art. 148 II c', 'descricao': 'adentrar à APM/ES fora do expediente administrativo, deixando de apresentar-se ao Oficial de Dia ou ao Fiscal de Dia;'},
{'artigo': 'Art. 148 II d', 'descricao': 'adentrar ao quartel em trajes não previstos pela APM/ES;,'},
{'artigo': 'Art. 148 II e', 'descricao': 'conduzir civis ou militares de outras unidades ao interior de vestiários, salas de aula e outras dependências da APM/ES, salvo com autorização do Oficial de Dia ou autoridade superior a este;'},
{'artigo': 'Art. 148 II f', 'descricao': 'sair do quartel com uniforme de educação física ou outros uniformes para os quais o trânsito externo seja vedado pelo regulamento específico, exceto em turmas, com a devida programação;'},
{'artigo': 'Art. 148 II g', 'descricao': 'adentrar em alojamento de superior ou de precedente hierárquico, de público de mesmo sexo, salvo por motivo de serviço ou devidamente autorizado;'},
{'artigo': 'Art. 148 II h', 'descricao': 'realizar refeição no interior de veículos ou em outro local não autorizado neste Manual.,'},
{'artigo': 'Art. 148 II i', 'descricao': 'fazer uso de equipamentos eletrônicos ou estar de posse de apostilas ou livros pelos alunos enquanto estiver aguardando atendimento médico agendado ou de emergência na Seção de Saúde;,'},
{'artigo': 'Art. 148 II j', 'descricao': 'realizar atividade que quebre o silêncio na recepção e no entorno da Seção de Saúde;,'},
{'artigo': 'Art. 148 II k', 'descricao': 'permanecer no interior ou entorno da Seção de Saúde, sem necessitar de atendimento médico, exceto para os casos de alunos que auxiliem no transporte em razão de emergência ou dificuldade de mobilidade da pessoa a ser atendida.'},
{'artigo': 'Art. 148 III a', 'descricao': 'desrespeitar regras de trânsito em área sob administração militar, na condução de veículo particular ou viatura militar;'},
{'artigo': 'Art. 148 III b', 'descricao': 'desrespeitar regras de trânsito, em via pública, com veículo particular;'},
{'artigo': 'Art. 148 III c', 'descricao': 'manter, introduzir ou fazer uso de bebidas alcoólicas nas dependências de Organização Militar;'},
{'artigo': 'Art. 148 III d', 'descricao': 'ausentar-se de instrução ou local em que deva permanecer, sem autorização;'},
{'artigo': 'Art. 148 III e', 'descricao': 'fazer a troca de vestimentas ou uniformes em locais diversos do vestiário específico;,'},
{'artigo': 'Art. 148 III f', 'descricao': 'pernoitar na APM/ES o discente não alojado, sem a devida autorização do Oficial de Dia ou autoridade superior a este, exceto quando de serviço interno;'},
{'artigo': 'Art. 148 III g', 'descricao': 'adentrar em alojamento diverso, de público de outro sexo, não estando em serviço ou não cumprindo os procedimentos definidos pela Divisão Acadêmica;'},
{'artigo': 'Art. 148 III h', 'descricao': 'não cumprir as orientações dos profissionais civis e militares lotados na Seção de Saúde no que se relaciona às condutas de atendimento, sobretudo quanto à classificação de risco e ordem de atendimento, ou desacatar os profissionais durante o atendimento.'},
{'artigo': 'Art. 149 I a', 'descricao': 'não saber os nomes e as funções dos Oficiais da APM/ES;,'},
{'artigo': 'Art. 149 II a', 'descricao': 'adotar atitude não condizente para com o seu subordinado;,'},
{'artigo': 'Art. 149 II b', 'descricao': 'não conhecer o Comandante da APM/ES e os respectivos Oficiais desta Unidade;,'},
{'artigo': 'Art. 149 II c', 'descricao': 'deixar o subordinado quer uniformizado, quer em traje civil, de cumprimentar superior, uniformizado ou não, neste caso desde que o conheça, ou prestar-lhe as homenagens e sinais regulamentares de consideração e respeito previstos;'},
{'artigo': 'Art. 149 II d', 'descricao': 'deixar o discente, presente a solenidades internas ou externas onde se encontrar superior hierárquico, de saudá-lo de acordo com as normas regulamentares.'},
{'artigo': 'Art. 149 III a', 'descricao': 'dirigir-se à autoridade acima de seu superior imediato sem que esteja devidamente autorizado;,'},
{'artigo': 'Art. 149 III b', 'descricao': 'determinar que alunos subordinados confeccionem trabalho escolar, limpem armamento ou façam qualquer outra incumbência que seja de sua exclusiva competência;'},
{'artigo': 'Art. 149 III c', 'descricao': 'dirigir-se ao Comandante Geral, Subcomandante, Chefe do Estado Maior Geral, Comandantes Intermediários ou Diretores, sem autorização do Comandante da APM/ES;'},
{'artigo': 'Art. 149 III d', 'descricao': 'tentar, por qualquer meio, obter a interferência de autoridades externas, civis ou militares, em assuntos da APM/ES, com o objetivo de modificar decisão de superior hierárquico ou adequá-la ao seu interesse.'},
{'artigo': 'Art. 150 I a', 'descricao': 'deixar de apresentar material escolar exigido pelo respectivo instrutor para aula ou instrução teórica ou prática.,'},
{'artigo': 'Art. 150 II a', 'descricao': 'deixar de entregar trabalho escolar no prazo estabelecido;,'},
{'artigo': 'Art. 150 II b', 'descricao': 'demonstrar falta de interesse e/ou vivacidade ou sinais de sonolência durante aula, seminário, palestra, instrução e outras atividades relacionadas ao ensino;'},
{'artigo': 'Art. 150 II c', 'descricao': 'entregar trabalho escolar mal elaborado e/ou sem o devido zelo;,'},
{'artigo': 'Art. 150 II d', 'descricao': 'não possuir durante as avaliações o material escolar necessário (lápis, borracha, caneta, etc.);'},
{'artigo': 'Art. 150 II e', 'descricao': 'deixar peças de fardamento, material escolar, ou qualquer outro objeto, em cima da carteira, fora do horário de aula;'},
{'artigo': 'Art. 150 II f', 'descricao': 'sair de sala durante as aulas, sem autorização do professor, do Chefe de Curso, ou sem prescrição médica.'},
{'artigo': 'Art. 150 III a', 'descricao': 'dormir durante instrução, aula, palestra, seminário ou outro ato relacionado ao ensino;'},
{'artigo': 'Art. 150 III b', 'descricao': 'utilizar equipamentos eletroeletrônicos durante instrução, aula, palestra ou outro ato relacionado ao ensino, sem autorização;'},
{'artigo': 'Art. 150 III c', 'descricao': 'faltar a qualquer tipo de prova, teste ou exame sem motivo justificável;'},
{'artigo': 'Art. 150 III d', 'descricao': 'utilizar ou manusear telefone celular, ou qualquer outro aparelho eletrônico de sua posse ou permitir que estes equipamentos emitam sinais sonoros de qualquer tipo durante os desfiles matinais, treinamentos e solenidades, nas salas de aula ou outras atividades determinadas pelo Chefe da Divisão Acadêmica, salvo se houver autorização do professor, Chefe de Curso ou Comando da respectiva Escola;'},
{'artigo': 'Art. 150 III e', 'descricao': 'fraudar ou tentar fraudar qualquer avaliação;,'},
{'artigo': 'Art. 150 III f', 'descricao': 'plagiar trabalho escolar, monografia ou trabalho de conclusão de curso, no todo ou em parte;'},
{'artigo': 'Art. 150 III g', 'descricao': 'plagiar recurso de avaliação;,'},
{'artigo': 'Art. 150 III h', 'descricao': 'ler jornais, revistas ou qualquer outro material estranho à atividade acadêmica que esteja sendo ministrada.'},
{'artigo': 'Art. 151 I a', 'descricao': 'prestar anúncio incorreto;,'},
{'artigo': 'Art. 151 I não', 'descricao': 'não se apresentar a superior hierárquico ou retirar-se de sua presença, sem obediência às normas regulamentares;'},
{'artigo': 'Art. 151 I proceder', 'descricao': 'proceder com a apresentação pessoal de maneira incorreta;,'},
{'artigo': 'Art. 151 I d', 'descricao': 'durante formaturas ou treinamentos, mexer-se, rir, falar sem autorização ou se portar de forma incorreta;'},
{'artigo': 'Art. 151 I e', 'descricao': 'dar o Comando de "À Vontade" à tropa formada, sem autorização de superior ou precedente hierárquico;'},
{'artigo': 'Art. 151 I f', 'descricao': 'não saber cantar o hino previsto no hinário;,'},
{'artigo': 'Art. 151 I g', 'descricao': 'sentar-se quando a tropa estiver formada;,'},
{'artigo': 'Art. 151 I h', 'descricao': 'não cumprir as normas de apresentação, procedimentos, formas de tratamento e precedência, previstos nos regulamentos militares;'},
{'artigo': 'Art. 151 I i', 'descricao': 'dirigir-se a superior, quando na APM/ES ou em serviço, tratando-o ou a ele se referindo, sem designar o grau hierárquico;'},
{'artigo': 'Art. 151 I j entrar em forma conduzindo objetos materiais', 'descricao': 'ou conduzir bolsas à tira colo ou dependuradas nos ombros.,'},
{'artigo': 'Art. 151 II a', 'descricao': 'deixar de prestar continência de tropa a Oficial;,'},
{'artigo': 'Art. 151 II b', 'descricao': 'não fazer o alto ao prestar continência ao Comandante da Unidade, na primeira vez que o encontrar, no interior da APM/ES;'},
{'artigo': 'Art. 151 II c', 'descricao': 'descumprir outras normas do Regulamento de Continências.,'},
{'artigo': 'Art. 151 III deixar', 'descricao': 'deixar de prestar continência individual regulamentar;,'},
{'artigo': 'Art. 151 III deixar', 'descricao': 'deixar de prestar ao superior ou precedente as manifestações de respeito previstas no Regulamento de Continências;,'},
{'artigo': 'Art. 151 III deixar', 'descricao': 'deixar de anunciar a presença de superior ou precedente ao adentrar em recinto.,'},
{'artigo': 'Art. 152 I a', 'descricao': 'não preservar a limpeza das instalações;,'},
{'artigo': 'Art. 152 I b', 'descricao': 'deixar cama desarrumada e/ou suja;,'},
{'artigo': 'Art. 152 I c', 'descricao': 'deixar armário desarrumado.,'},
{'artigo': 'Art. 152 II a', 'descricao': 'deixar vestiário, armário, sala de aula ou qualquer outro ambiente sujo ou desorganizado, quando responsável pela limpeza e organização;'},
{'artigo': 'Art. 152 II b', 'descricao': 'deixar vestiário, armário ou sala de aula aberta ou destrancada, quando responsável pela limpeza e organização;'},
{'artigo': 'Art. 152 II c', 'descricao': 'deixar luzes acesas, ventiladores ou ar condicionado ligados quando não for necessário o seu uso;'},
{'artigo': 'Art. 152 II d', 'descricao': 'abandonar equipamento ou material de uso pessoal;,'},
{'artigo': 'Art. 152 II e', 'descricao': 'deixar aberta a porta de seu armário individual, escaninho ou de sala/dependência que seja de sua responsabilidade o trancamento;'},
{'artigo': 'Art. 152 II f', 'descricao': 'deixar de colocar etiqueta de identificação em armários, carteiras, cadeiras, material escolar e qualquer outro material utilizado pelo discente no âmbito da APM/ES.'},
{'artigo': 'Art. 152 III a', 'descricao': 'guardar, no vestiário ou no escaninho, armamento, munição ou quaisquer objetos que prejudiquem seu bom aspecto ou que possa causar danos à vida ou à saúde dos alunos;'},
{'artigo': 'Art. 152 III b', 'descricao': 'sujar paredes/portas das instalações da APM/ES;,'},
{'artigo': 'Art. 152 III c', 'descricao': 'danificar bem patrimonial do Estado posto ou não sob sua guarda.,'},
{'artigo': 'Art. 153 I a', 'descricao': 'faltar com a higiene pessoal;,'},
{'artigo': 'Art. 153 I b', 'descricao': 'não manter as unhas curtas;,'},
{'artigo': 'Art. 153 I c', 'descricao': 'transitar descalço na área externa ao dojô ou qualquer outra área da APM/ES sem a devida autorização.,'},
{'artigo': 'Art. 153 II a', 'descricao': 'Cortar, os discentes do sexo masculino, o cabelo fora dos padrões estabelecidos ou não manter adequadamente;'},
{'artigo': 'Art. 153 II b', 'descricao': 'não fazer a barba corretamente;,'},
{'artigo': 'Art. 153 II c', 'descricao': 'deixar de manter, as discentes do sexo feminino que possuam os cabelos longos ou médios, o penteado no formato de coque (cabelo preso), de acordo com o RUIPMES;'},
{'artigo': 'Art. 153 II d', 'descricao': 'utilizar maquiagem exagerada ou chamativa nas atividades de instrução diárias, em desconformidade com o previsto no RUIPMES;'},
{'artigo': 'Art. 153 II e', 'descricao': 'pintar as unhas com esmalte de cor intensa ou brilhante ou utilizar de qualquer tipo de desenho ou aplique;,'},
{'artigo': 'Art. 153 III a', 'descricao': 'deixar de fazer a barba;,'},
{'artigo': 'Art. 153 III b', 'descricao': 'deixar o/a discente de cortar o cabelo na data prevista pela escola.,'},
{'artigo': 'Art. 154 I a', 'descricao': 'deixar de informar ao Xerife de turma o seu destino, quando não for entrar em forma;'},
{'artigo': 'Art. 154 I b', 'descricao': 'mascar goma quando estiver uniformizado;,'},
{'artigo': 'Art. 154 I c', 'descricao': 'andar, uniformizado, com as mãos nos bolsos.'},
{'artigo': 'Art. 154 II a', 'descricao': 'não cumprir determinação médica;,'},
{'artigo': 'Art. 154 II b', 'descricao': 'não encaminhar à Escola guia de saúde ou guia de atendimento médico ou odontológico, após ser consultado ou atendido;'},
{'artigo': 'Art. 154 II c', 'descricao': 'Trabalhar mal ou descumprir as normas regulamentares na esfera de suas atribuições quando no desempenho de alguma das funções especificadas no Título XII do Manual do Aluno.,'},
{'artigo': 'Art. 154 III a', 'descricao': 'falta de presteza no cumprimento de ordem superior;,'},
{'artigo': 'Art. 154 III b', 'descricao': 'não obedecer às ordens ou dificultar o comando do Xerife;,'},
{'artigo': 'Art. 154 III c', 'descricao': 'esquivar-se de suas obrigações acadêmico-funcionais;,'},
{'artigo': 'Art. 154 III d', 'descricao': 'deixar de cumprir ordens legais ou regulamentares do professor militar ou civil, Chefe de Curso e os que são de hierarquia superior ou os que tenham precedência hierárquica;'},
{'artigo': 'Art. 154 III e', 'descricao': 'deixar de entrar em forma sem motivo justificado;,'},
{'artigo': 'Art. 154 III f', 'descricao': 'alegar desconhecimento das normas previstas neste Manual;,'},
{'artigo': 'Art. 154 III g', 'descricao': 'alegar desconhecimento de lei, norma ou regulamento;'},
{'artigo': 'Art. 154 III h', 'descricao': 'praticar qualquer ação ou omissão não previstas neste Manual e que afetem a disciplina, o respeito e o relacionamento coletivo entre o corpo discente;'},
{'artigo': 'Art. 154 III i', 'descricao': 'publicar comentários, fotografias ou vídeos em rede sociais e aplicativos de mensagem que mostrem os treinamentos ministrados durante o curso, para evitar que as estratégias da PMES, ao serem expostas, percam a sua efetividade;'},
{'artigo': 'Art. 154 III j', 'descricao': 'identificar-se o aluno em curso de formação inicial como policial militar em perfis de redes sociais, expondo sua imagem uniformizado;'},
{'artigo': 'Art. 154 III k', 'descricao': 'manifestar-se em redes sociais ou outros canais de comunicação sobre assuntos relacionados às atividades acadêmicas, administrativas ou operacionais da Polícia Militar, sem autorização prévia do Comando da APM/ES;'},
{'artigo': 'Art. 154 III l', 'descricao': 'deixar de acatar as normas previstas, em vigor na OM e demais regras registradas neste Manual do Aluno não tipificadas em artigo específico do Capítulo III - das Transgressões Escolares; (trouxe para o final)'},
]